language: ruby
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
env:
  - PUPPET_GEM_VERSION=2.7.26
  - PUPPET_GEM_VERSION=3.7.5
matrix:
  fast_finish: true
notifications:
  email: false
